---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Copy manila configs
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner|default(manila_system_user_name) }}"
    group: "{{ item.group|default(manila_system_group_name) }}"
    mode: "0644"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "manila.conf.j2"
      dest: "/etc/manila/manila.conf"
      config_overrides: "{{ manila_manila_conf_overrides }}"
      config_type: "ini"
    - src: "api-paste.ini.j2"
      dest: "/etc/manila/api-paste.ini"
      config_overrides: "{{ manila_api_paste_ini_overrides }}"
      config_type: "ini"
    - src: "rootwrap.conf.j2"
      dest: "/etc/manila/rootwrap.conf"
      owner: "root"
      group: "root"
      config_overrides: "{{ manila_rootwrap_conf_overrides }}"
      config_type: "ini"
    - src: "policy.json.j2"
      dest: "/etc/manila/policy.json"
      config_overrides: "{{ manila_policy_overrides }}"
      config_type: "json"
  notify:
    - Restart manila services
  tags:
    - manila-config

- name: Drop manila configs
  copy:
    src: "rootwrap.d/share.filters"
    dest: "/etc/manila/rootwrap.d/share.filters"
    owner: "root"
    group: "root"
  notify:
    - Restart manila services
  tags:
    - manila-config

# - name: Ensure manila tgt include
#   lineinfile:
#     dest: /etc/tgt/targets.conf
#     line: "include /var/lib/manila/volumes/*"
#     state: present
#   notify: Ensure tgt service restarted
#   when:
#     - inventory_hostname in groups['manila_volume']
#     - manila_backend_lvm_inuse | bool
#   tags:
#     - manila-tgt

# - name: Create nfs shares export file
#   template:
#     src: nfs_shares.j2
#     dest: "{{ manila_nfs_client.nfs_shares_config }}"
#   when:
#     - manila_nfs_client is defined
#     - inventory_hostname in groups['manila_volume']
#   tags:
#     - manila-nfs

- name: Get manila command path
  command: which manila
  register: manila_command_path
  when:
    - not manila_venv_enabled | bool
  tags:
    - manila-command-bin

- name: Set manila command path
  set_fact:
    manila_bin: "{{ manila_command_path.stdout | dirname }}"
  when:
    - not manila_venv_enabled | bool
  tags:
    - manila-command-bin

- name: Drop sudoers file
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/{{ manila_system_user_name }}_sudoers"
    mode: "0440"
    owner: "root"
    group: "root"
  tags:
    - sudoers
    - manila-sudoers
